apiVersion: batch/v1
kind: Job
metadata:
  name: todo-table2
  namespace: todo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: postgresql-client
          image: postgres:12
          imagePullPolicy: Always
          env:
            - name: PGPASSWORD
              value: admin
          command: ["psql"]
          args:
            [
              "--host=postgresql",
              "--username=admin",
              "--no-password",
              "--dbname=todo",
              "--command=create table Todo2 (id bigint not null,completed boolean not null,ordering integer,title varchar(255),url varchar(255),primary key (id));",
            ]
      restartPolicy: Never
  backoffLimit: 1